baseurl: ""
github_account: "https://github.com/Scthe"
title: "Scthe's blog"
tagline: 'Scthe blog'

markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
  syntax_highlighter: pygments


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Scthe"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Scthe"

exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
