baseurl: ""
github_account: "https://github.com/Scthe"
title: "Scthe's blog"
description: "Mostly some programming stuff"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Scthe"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Scthe"

exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "references"
  - "node_modules"
